.TH asciiplanets 1 "2017-12-24" "asciiplanets" "User Commands"
.\" --------------------------------------------------------------------
.SH NAME
asciiplanets-interactive \- Interactive wrapper for asciiplanets
.\" --------------------------------------------------------------------
.SH SYNOPSIS
\fBasciiplanets-interactive\fP
[\fIOPTION\fP]...
.\" --------------------------------------------------------------------
.SH DESCRIPTION
Runs \fBasciiplanets\fP interactively. You can choose date and radius
with immediate feedback.
.\" --------------------------------------------------------------------
.SH OPTIONS
Accepts all options that \fBasciiplanets\fP accepts. However, specifying
\fB\-\-date\fP or \fB\-\-radius\fP does not make sense.
.\" --------------------------------------------------------------------
.SH KEYS
.TP
\fBd\fP and \fBD\fP
Go forward/backward one day.
.TP
\fBm\fP and \fBM\fP
Go forward/backward one month.
.TP
\fBy\fP and \fBY\fP
Go forward/backward one year.
.TP
\fBj\fP and \fBk\fP
Increase/decrease visible radius. In other words, zoom out/in.
.TP
\fBi\fP and \fBo\fP
Jump to inner/outer solar system.
.TP
\fBn\fP
Reset date to \fBnow\fP.
.TP
\fBh\fP
Show this manpage.
.TP
\fBq\fP
Quit.
.\" --------------------------------------------------------------------
.SH LICENSE
\fBasciiplanets\fP is released under the MIT license. See the
accompanying \fILICENSE\fP file.
.\" --------------------------------------------------------------------
.SH HISTORY
\fBasciiplanets\fP was originally written by Peter Hofmann. The project
was started in February 2015.
